# Generated by Django 5.1.1 on 2024-10-16 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rankings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamResults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_no', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('board', models.CharField(max_length=100)),
                ('father_name', models.CharField(max_length=100)),
                ('group', models.CharField(max_length=100)),
                ('mother_name', models.CharField(max_length=100)),
                ('session', models.CharField(max_length=100)),
                ('reg_no', models.CharField(max_length=100)),
                ('type_of_result', models.CharField(max_length=100)),
                ('institute', models.CharField(max_length=100)),
                ('result', models.CharField(max_length=100)),
                ('gpa', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bangla', models.IntegerField()),
                ('english', models.IntegerField()),
                ('ict', models.IntegerField()),
                ('physics', models.IntegerField()),
                ('chemistry', models.IntegerField()),
                ('biology', models.IntegerField()),
                ('higher_math', models.IntegerField()),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Rankings.examresults')),
            ],
        ),
        migrations.DeleteModel(
            name='ExamResult',
        ),
    ]
