# Generated by Django 5.1.1 on 2024-10-16 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rankings', '0002_examresults_marks_delete_examresult'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examresults',
            name='gpa',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
