# Generated by Django 5.1.1 on 2024-10-16 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rankings', '0003_alter_examresults_gpa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examresults',
            name='board',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='examresults',
            name='father_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='examresults',
            name='group',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='examresults',
            name='institute',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='examresults',
            name='mother_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='examresults',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='examresults',
            name='reg_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='examresults',
            name='result',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='examresults',
            name='session',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='examresults',
            name='type_of_result',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='marks',
            name='bangla',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='marks',
            name='biology',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='marks',
            name='chemistry',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='marks',
            name='english',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='marks',
            name='higher_math',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='marks',
            name='ict',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='marks',
            name='physics',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
