# Generated by Django 5.1.1 on 2024-10-17 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rankings', '0004_alter_examresults_board_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='marks',
            name='accounting',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='marks',
            name='civics',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='marks',
            name='economics',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='marks',
            name='finance',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='marks',
            name='history',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='marks',
            name='logic',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='marks',
            name='management',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.RenameModel(
            old_name='ExamResults',
            new_name='StudentInfo',
        ),
        migrations.CreateModel(
            name='Rankings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_marks_rank', models.IntegerField(blank=True, null=True)),
                ('group_subject_marks_rank', models.IntegerField(blank=True, null=True)),
                ('exams_given_marks_rank', models.IntegerField(blank=True, null=True)),
                ('group_rank', models.IntegerField(blank=True, null=True)),
                ('college_rank', models.IntegerField(blank=True, null=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Rankings.studentinfo')),
            ],
        ),
    ]
