# Generated by Django 5.1.1 on 2024-10-18 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rankings', '0005_marks_accounting_marks_civics_marks_economics_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marks',
            name='accounting',
        ),
        migrations.RemoveField(
            model_name='marks',
            name='biology',
        ),
        migrations.RemoveField(
            model_name='marks',
            name='chemistry',
        ),
        migrations.RemoveField(
            model_name='marks',
            name='civics',
        ),
        migrations.RemoveField(
            model_name='marks',
            name='economics',
        ),
        migrations.RemoveField(
            model_name='marks',
            name='english',
        ),
        migrations.RemoveField(
            model_name='marks',
            name='finance',
        ),
        migrations.RemoveField(
            model_name='marks',
            name='higher_math',
        ),
        migrations.RemoveField(
            model_name='marks',
            name='history',
        ),
        migrations.RemoveField(
            model_name='marks',
            name='ict',
        ),
        migrations.RemoveField(
            model_name='marks',
            name='logic',
        ),
        migrations.RemoveField(
            model_name='marks',
            name='management',
        ),
        migrations.RemoveField(
            model_name='marks',
            name='physics',
        ),
        migrations.AlterField(
            model_name='marks',
            name='bangla',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.DeleteModel(
            name='Rankings',
        ),
    ]
