# Generated by Django 5.1.1 on 2024-10-18 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rankings', '0007_marks_accounting_marks_biology_marks_chemistry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentinfo',
            name='rank',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
