# Generated by Django 5.1.2 on 2025-07-10 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rankings', '0008_studentinfo_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='marks',
            name='agriculture',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='marks',
            name='bangladesh_world',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='marks',
            name='business_ent',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='marks',
            name='finance_banking',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='marks',
            name='general_science',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='marks',
            name='geography',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='marks',
            name='history_bd',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='marks',
            name='islam_moral',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='marks',
            name='math',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='marks',
            name='music',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
