# Generated by Django 5.1.2 on 2025-07-10 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rankings', '0009_marks_agriculture_marks_bangladesh_world_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentinfo',
            name='exam_type',
            field=models.CharField(choices=[('HSC', 'HSC'), ('SSC', 'SSC')], default='HSC', max_length=10),
        ),
    ]
