# Generated by Django 5.1.2 on 2025-07-10 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rankings', '0010_studentinfo_exam_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinfo',
            name='roll_no',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='studentinfo',
            unique_together={('roll_no', 'exam_type')},
        ),
    ]
