# Generated by Django 5.1.2 on 2025-07-10 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rankings', '0011_alter_studentinfo_roll_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='marks',
            name='career_education',
            field=models.IntegerField(default=0, verbose_name='Career Education'),
        ),
        migrations.AddField(
            model_name='marks',
            name='physical_education',
            field=models.IntegerField(default=0, verbose_name='Physical Education, Health and Sports'),
        ),
    ]
