# Generated by Django 5.1.2 on 2025-07-11 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rankings', '0012_marks_career_education_marks_physical_education'),
    ]

    operations = [
        migrations.AddField(
            model_name='marks',
            name='buddha_moral',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='marks',
            name='christian_moral',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='marks',
            name='hindu_moral',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
