# Generated by Django 5.1.2 on 2026-07-27 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rankings', '0013_marks_buddha_moral_marks_christian_moral_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinfo',
            name='exam_type',
            field=models.CharField(choices=[('HSC_2024', 'HSC 2024'), ('SSC_2025', 'SSC 2025'), ('HSC_2025', 'HSC 2025')], default='HSC_2024', max_length=10),
        ),
        migrations.AddIndex(
            model_name='marks',
            index=models.Index(fields=['total_marks'], name='Rankings_ma_total_m_f39360_idx'),
        ),
        migrations.AddIndex(
            model_name='studentinfo',
            index=models.Index(fields=['exam_type', 'group', 'rank'], name='Rankings_st_exam_ty_d3ebf3_idx'),
        ),
        migrations.AddIndex(
            model_name='studentinfo',
            index=models.Index(fields=['institute'], name='Rankings_st_institu_6c4477_idx'),
        ),
    ]
