# Generated by Django 5.1.2 on 2026-07-27 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rankings', '0015_normalize_exam_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_type', models.CharField(max_length=10, unique=True)),
                ('label', models.CharField(max_length=50)),
                ('rankings_published', models.BooleanField(default=False)),
                ('scrape_complete', models.BooleanField(default=False)),
                ('last_ranked_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
