# Generated by Django 5.1.2 on 2026-07-27 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rankings', '0017_seed_examsets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinfo',
            name='exam_type',
            field=models.CharField(choices=[('HSC_2024', 'HSC 2024'), ('SSC_2025', 'SSC 2025'), ('HSC_2025', 'HSC 2025'), ('SSC_2026', 'SSC 2026')], default='HSC_2024', max_length=10),
        ),
    ]
