# Generated by Django 5.1.2 on 2026-07-27 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rankings', '0019_normalize_ssc_2025_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinfo',
            name='exam_type',
            field=models.CharField(default='HSC_2024', max_length=10),
        ),
    ]
